# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faas.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfaas.proto\x12\x04\x66\x61\x61s\"\x84\x01\n\x0b\x46\x61\x61sRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\tbatchsize\x18\x02 \x01(\r\x12\x19\n\x11runtimeInMilliSec\x18\x03 \x01(\r\x12\x1c\n\x14gpuMemoryInMebiBytes\x18\x04 \x01(\r\x12\x18\n\x0cpromptTensor\x18\x05 \x03(\x02\x42\x02\x10\x01\"r\n\tFaasReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1a\n\x12\x64urationInMicroSec\x18\x02 \x01(\r\x12\x1c\n\x14gpuMemoryInMebiBytes\x18\x03 \x01(\r\x12\x1a\n\x0epromptGradient\x18\x04 \x03(\x02\x42\x02\x10\x01\x32;\n\x08\x45xecutor\x12/\n\x07\x45xecute\x12\x11.faas.FaasRequest\x1a\x0f.faas.FaasReply\"\x00\x42\rZ\x0bproto/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'faas_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\013proto/proto'
  _FAASREQUEST.fields_by_name['promptTensor']._options = None
  _FAASREQUEST.fields_by_name['promptTensor']._serialized_options = b'\020\001'
  _FAASREPLY.fields_by_name['promptGradient']._options = None
  _FAASREPLY.fields_by_name['promptGradient']._serialized_options = b'\020\001'
  _FAASREQUEST._serialized_start=21
  _FAASREQUEST._serialized_end=153
  _FAASREPLY._serialized_start=155
  _FAASREPLY._serialized_end=269
  _EXECUTOR._serialized_start=271
  _EXECUTOR._serialized_end=330
# @@protoc_insertion_point(module_scope)
