# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faas.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfaas.proto\x12\x04\x66\x61\x61s\"T\n\x0b\x46\x61\x61sRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x19\n\x11runtimeInMilliSec\x18\x02 \x01(\r\x12\x19\n\x11memoryInMebiBytes\x18\x03 \x01(\r\"Q\n\tFaasReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1a\n\x12\x64urationInMicroSec\x18\x02 \x01(\r\x12\x17\n\x0fmemoryUsageInKb\x18\x03 \x01(\r2;\n\x08\x45xecutor\x12/\n\x07\x45xecute\x12\x11.faas.FaasRequest\x1a\x0f.faas.FaasReply\"\x00\x42\x33Z1github.com/vhive-serverless/loader/workload/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'faas_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1github.com/vhive-serverless/loader/workload/proto'
  _globals['_FAASREQUEST']._serialized_start=20
  _globals['_FAASREQUEST']._serialized_end=104
  _globals['_FAASREPLY']._serialized_start=106
  _globals['_FAASREPLY']._serialized_end=187
  _globals['_EXECUTOR']._serialized_start=189
  _globals['_EXECUTOR']._serialized_end=248
# @@protoc_insertion_point(module_scope)
