//
// Set up:
// $ go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
// $ go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
//
// Add `<GOPATH>/bin` to your $PATH:
// OR (!suboptimal since it overwrites $PATH by appending an additional
// line as opposed to change it directly)
// $ echo "export PATH=$PATH:$(go env GOPATH)/bin" >> ~/.profile
// $ source ~/.profile
// OR temporarily
// $ export PATH="$PATH:$(go env GOPATH)/bin"

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: gptfaas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GPTFaasRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message              string    `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                            // Text message field.
	Batchsize            uint32    `protobuf:"varint,2,opt,name=batchsize,proto3" json:"batchsize,omitempty"`                       // batch size
	RuntimeInMilliSec    uint32    `protobuf:"varint,3,opt,name=runtimeInMilliSec,proto3" json:"runtimeInMilliSec,omitempty"`       // Execution runtime [ms].
	GpuMemoryInMebiBytes uint32    `protobuf:"varint,4,opt,name=gpuMemoryInMebiBytes,proto3" json:"gpuMemoryInMebiBytes,omitempty"` // Request memory usage [MiB].
	PromptTensor         []float32 `protobuf:"fixed32,5,rep,packed,name=promptTensor,proto3" json:"promptTensor,omitempty"`         // prompt inputs
}

func (x *GPTFaasRequest) Reset() {
	*x = GPTFaasRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gptfaas_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPTFaasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPTFaasRequest) ProtoMessage() {}

func (x *GPTFaasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gptfaas_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPTFaasRequest.ProtoReflect.Descriptor instead.
func (*GPTFaasRequest) Descriptor() ([]byte, []int) {
	return file_gptfaas_proto_rawDescGZIP(), []int{0}
}

func (x *GPTFaasRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GPTFaasRequest) GetBatchsize() uint32 {
	if x != nil {
		return x.Batchsize
	}
	return 0
}

func (x *GPTFaasRequest) GetRuntimeInMilliSec() uint32 {
	if x != nil {
		return x.RuntimeInMilliSec
	}
	return 0
}

func (x *GPTFaasRequest) GetGpuMemoryInMebiBytes() uint32 {
	if x != nil {
		return x.GpuMemoryInMebiBytes
	}
	return 0
}

func (x *GPTFaasRequest) GetPromptTensor() []float32 {
	if x != nil {
		return x.PromptTensor
	}
	return nil
}

type GPTFaasReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message              string    `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                            // Text message field.
	DurationInSec        uint32    `protobuf:"varint,2,opt,name=durationInSec,proto3" json:"durationInSec,omitempty"`               // Execution latency [µs].
	GpuMemoryInMebiBytes uint32    `protobuf:"varint,3,opt,name=gpuMemoryInMebiBytes,proto3" json:"gpuMemoryInMebiBytes,omitempty"` // Memory usage [MiB].
	PromptGradient       []float32 `protobuf:"fixed32,4,rep,packed,name=promptGradient,proto3" json:"promptGradient,omitempty"`     // prompt gradients
}

func (x *GPTFaasReply) Reset() {
	*x = GPTFaasReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gptfaas_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPTFaasReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPTFaasReply) ProtoMessage() {}

func (x *GPTFaasReply) ProtoReflect() protoreflect.Message {
	mi := &file_gptfaas_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPTFaasReply.ProtoReflect.Descriptor instead.
func (*GPTFaasReply) Descriptor() ([]byte, []int) {
	return file_gptfaas_proto_rawDescGZIP(), []int{1}
}

func (x *GPTFaasReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GPTFaasReply) GetDurationInSec() uint32 {
	if x != nil {
		return x.DurationInSec
	}
	return 0
}

func (x *GPTFaasReply) GetGpuMemoryInMebiBytes() uint32 {
	if x != nil {
		return x.GpuMemoryInMebiBytes
	}
	return 0
}

func (x *GPTFaasReply) GetPromptGradient() []float32 {
	if x != nil {
		return x.PromptGradient
	}
	return nil
}

var File_gptfaas_proto protoreflect.FileDescriptor

var file_gptfaas_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x70, 0x74, 0x66, 0x61, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x67, 0x70, 0x74, 0x66, 0x61, 0x61, 0x73, 0x22, 0xd2, 0x01, 0x0a, 0x0e, 0x47, 0x50, 0x54,
	0x46, 0x61, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x63, 0x68, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x62, 0x61, 0x74, 0x63, 0x68, 0x73,
	0x69, 0x7a, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x6e,
	0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x53, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11,
	0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x53, 0x65,
	0x63, 0x12, 0x32, 0x0a, 0x14, 0x67, 0x70, 0x75, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x49, 0x6e,
	0x4d, 0x65, 0x62, 0x69, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x14, 0x67, 0x70, 0x75, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x4d, 0x65, 0x62, 0x69,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x54,
	0x65, 0x6e, 0x73, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x03, 0x28, 0x02, 0x42, 0x02, 0x10, 0x01, 0x52,
	0x0c, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x22, 0xae, 0x01,
	0x0a, 0x0c, 0x47, 0x50, 0x54, 0x46, 0x61, 0x61, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x53, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0d, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x53, 0x65, 0x63, 0x12, 0x32,
	0x0a, 0x14, 0x67, 0x70, 0x75, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x4d, 0x65, 0x62,
	0x69, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x14, 0x67, 0x70,
	0x75, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x4d, 0x65, 0x62, 0x69, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x12, 0x2a, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x47, 0x72, 0x61, 0x64,
	0x69, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x02, 0x42, 0x02, 0x10, 0x01, 0x52, 0x0e,
	0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x47, 0x72, 0x61, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x32, 0x47,
	0x0a, 0x08, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x12, 0x3b, 0x0a, 0x07, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x67, 0x70, 0x74, 0x66, 0x61, 0x61, 0x73, 0x2e,
	0x47, 0x50, 0x54, 0x46, 0x61, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x67, 0x70, 0x74, 0x66, 0x61, 0x61, 0x73, 0x2e, 0x47, 0x50, 0x54, 0x46, 0x61, 0x61, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x67, 0x70, 0x74, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_gptfaas_proto_rawDescOnce sync.Once
	file_gptfaas_proto_rawDescData = file_gptfaas_proto_rawDesc
)

func file_gptfaas_proto_rawDescGZIP() []byte {
	file_gptfaas_proto_rawDescOnce.Do(func() {
		file_gptfaas_proto_rawDescData = protoimpl.X.CompressGZIP(file_gptfaas_proto_rawDescData)
	})
	return file_gptfaas_proto_rawDescData
}

var file_gptfaas_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gptfaas_proto_goTypes = []interface{}{
	(*GPTFaasRequest)(nil), // 0: gptfaas.GPTFaasRequest
	(*GPTFaasReply)(nil),   // 1: gptfaas.GPTFaasReply
}
var file_gptfaas_proto_depIdxs = []int32{
	0, // 0: gptfaas.Executor.Execute:input_type -> gptfaas.GPTFaasRequest
	1, // 1: gptfaas.Executor.Execute:output_type -> gptfaas.GPTFaasReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gptfaas_proto_init() }
func file_gptfaas_proto_init() {
	if File_gptfaas_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gptfaas_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPTFaasRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gptfaas_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPTFaasReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gptfaas_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gptfaas_proto_goTypes,
		DependencyIndexes: file_gptfaas_proto_depIdxs,
		MessageInfos:      file_gptfaas_proto_msgTypes,
	}.Build()
	File_gptfaas_proto = out.File
	file_gptfaas_proto_rawDesc = nil
	file_gptfaas_proto_goTypes = nil
	file_gptfaas_proto_depIdxs = nil
}
