# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gptfaas.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgptfaas.proto\x12\x07gptfaas\"\x87\x01\n\x0eGPTFaasRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\tbatchsize\x18\x02 \x01(\r\x12\x19\n\x11runtimeInMilliSec\x18\x03 \x01(\r\x12\x1c\n\x14gpuMemoryInMebiBytes\x18\x04 \x01(\r\x12\x18\n\x0cpromptTensor\x18\x05 \x03(\x02\x42\x02\x10\x01\"p\n\x0cGPTFaasReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x15\n\rdurationInSec\x18\x02 \x01(\r\x12\x1c\n\x14gpuMemoryInMebiBytes\x18\x03 \x01(\r\x12\x1a\n\x0epromptGradient\x18\x04 \x03(\x02\x42\x02\x10\x01\x32G\n\x08\x45xecutor\x12;\n\x07\x45xecute\x12\x17.gptfaas.GPTFaasRequest\x1a\x15.gptfaas.GPTFaasReply\"\x00\x42\x10Z\x0egptproto/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gptfaas_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\016gptproto/proto'
  _GPTFAASREQUEST.fields_by_name['promptTensor']._options = None
  _GPTFAASREQUEST.fields_by_name['promptTensor']._serialized_options = b'\020\001'
  _GPTFAASREPLY.fields_by_name['promptGradient']._options = None
  _GPTFAASREPLY.fields_by_name['promptGradient']._serialized_options = b'\020\001'
  _GPTFAASREQUEST._serialized_start=27
  _GPTFAASREQUEST._serialized_end=162
  _GPTFAASREPLY._serialized_start=164
  _GPTFAASREPLY._serialized_end=276
  _EXECUTOR._serialized_start=278
  _EXECUTOR._serialized_end=349
# @@protoc_insertion_point(module_scope)
