// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/faas.proto

package server

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FaasRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	RuntimeInMilliSec    uint32   `protobuf:"varint,2,opt,name=runtimeInMilliSec,proto3" json:"runtimeInMilliSec,omitempty"`
	MemoryInMebiBytes    uint32   `protobuf:"varint,3,opt,name=memoryInMebiBytes,proto3" json:"memoryInMebiBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FaasRequest) Reset()         { *m = FaasRequest{} }
func (m *FaasRequest) String() string { return proto.CompactTextString(m) }
func (*FaasRequest) ProtoMessage()    {}
func (*FaasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4886c8193ee7bbe7, []int{0}
}

func (m *FaasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaasRequest.Unmarshal(m, b)
}
func (m *FaasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaasRequest.Marshal(b, m, deterministic)
}
func (m *FaasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaasRequest.Merge(m, src)
}
func (m *FaasRequest) XXX_Size() int {
	return xxx_messageInfo_FaasRequest.Size(m)
}
func (m *FaasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FaasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FaasRequest proto.InternalMessageInfo

func (m *FaasRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *FaasRequest) GetRuntimeInMilliSec() uint32 {
	if m != nil {
		return m.RuntimeInMilliSec
	}
	return 0
}

func (m *FaasRequest) GetMemoryInMebiBytes() uint32 {
	if m != nil {
		return m.MemoryInMebiBytes
	}
	return 0
}

type FaasReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	LatencyInMicroSec    uint32   `protobuf:"varint,2,opt,name=latencyInMicroSec,proto3" json:"latencyInMicroSec,omitempty"`
	MemoryUsageInBytes   uint32   `protobuf:"varint,3,opt,name=memoryUsageInBytes,proto3" json:"memoryUsageInBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FaasReply) Reset()         { *m = FaasReply{} }
func (m *FaasReply) String() string { return proto.CompactTextString(m) }
func (*FaasReply) ProtoMessage()    {}
func (*FaasReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4886c8193ee7bbe7, []int{1}
}

func (m *FaasReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaasReply.Unmarshal(m, b)
}
func (m *FaasReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaasReply.Marshal(b, m, deterministic)
}
func (m *FaasReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaasReply.Merge(m, src)
}
func (m *FaasReply) XXX_Size() int {
	return xxx_messageInfo_FaasReply.Size(m)
}
func (m *FaasReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FaasReply.DiscardUnknown(m)
}

var xxx_messageInfo_FaasReply proto.InternalMessageInfo

func (m *FaasReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *FaasReply) GetLatencyInMicroSec() uint32 {
	if m != nil {
		return m.LatencyInMicroSec
	}
	return 0
}

func (m *FaasReply) GetMemoryUsageInBytes() uint32 {
	if m != nil {
		return m.MemoryUsageInBytes
	}
	return 0
}

func init() {
	proto.RegisterType((*FaasRequest)(nil), "faas.FaasRequest")
	proto.RegisterType((*FaasReply)(nil), "faas.FaasReply")
}

func init() { proto.RegisterFile("server/faas.proto", fileDescriptor_4886c8193ee7bbe7) }

var fileDescriptor_4886c8193ee7bbe7 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xbf, 0x4b, 0xc4, 0x30,
	0x18, 0x86, 0xad, 0x8a, 0xe7, 0x45, 0x44, 0x9a, 0xa9, 0x38, 0x1d, 0x07, 0xe2, 0x0d, 0xda, 0x80,
	0x8e, 0x6e, 0x07, 0x0a, 0x1d, 0x6e, 0xa9, 0xb8, 0xb8, 0xa5, 0xf1, 0xf5, 0x2e, 0x90, 0x1f, 0x35,
	0x49, 0xc5, 0xcc, 0xfe, 0xe3, 0x92, 0x0b, 0x42, 0xa1, 0xe2, 0xf6, 0x25, 0xcf, 0xf7, 0x92, 0x87,
	0x37, 0xa4, 0xf4, 0x70, 0x9f, 0x70, 0xec, 0x9d, 0x73, 0x5f, 0xf7, 0xce, 0x06, 0x4b, 0x8f, 0xd3,
	0xbc, 0xfc, 0x2e, 0xc8, 0xd9, 0x13, 0xe7, 0xbe, 0xc5, 0xc7, 0x00, 0x1f, 0x68, 0x45, 0x66, 0x1a,
	0xde, 0xf3, 0x2d, 0xaa, 0x62, 0x51, 0xac, 0xe6, 0xed, 0xef, 0x91, 0xde, 0x90, 0xd2, 0x0d, 0x26,
	0x48, 0x8d, 0xc6, 0x6c, 0xa4, 0x52, 0xf2, 0x19, 0xa2, 0x3a, 0x5c, 0x14, 0xab, 0xf3, 0x76, 0x0a,
	0xd2, 0xb6, 0x86, 0xb6, 0x2e, 0x36, 0x66, 0x83, 0x4e, 0xae, 0x63, 0x80, 0xaf, 0x8e, 0xf2, 0xf6,
	0x04, 0x24, 0x8b, 0x79, 0xb6, 0xe8, 0x55, 0xfc, 0xdf, 0x41, 0xf1, 0x00, 0x23, 0x52, 0x5a, 0x0a,
	0x67, 0x47, 0x0e, 0x13, 0x40, 0x6b, 0x42, 0xf3, 0x53, 0x2f, 0x29, 0xdc, 0x98, 0xb1, 0xc4, 0x1f,
	0xe4, 0xee, 0x81, 0x9c, 0x3e, 0x7e, 0x41, 0x0c, 0xc1, 0x3a, 0xca, 0xc8, 0x2c, 0xcf, 0xa0, 0x65,
	0xbd, 0x6f, 0x6d, 0xd4, 0xd2, 0xe5, 0xc5, 0xf8, 0xaa, 0x57, 0x71, 0x79, 0xb0, 0xbe, 0x7e, 0xbd,
	0xda, 0xca, 0xb0, 0x1b, 0xba, 0x5a, 0x58, 0xcd, 0x10, 0x76, 0xb7, 0xe0, 0x5e, 0x31, 0x70, 0x1f,
	0x95, 0xe5, 0x6f, 0x70, 0x2c, 0x7f, 0x41, 0x77, 0xb2, 0xaf, 0xff, 0xfe, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x4e, 0x18, 0xc8, 0x1f, 0x93, 0x01, 0x00, 0x00,
}
