# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sched_pb2 as sched__pb2


class ExecutorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/sched.Executor/Execute',
                request_serializer=sched__pb2.SchedRequest.SerializeToString,
                response_deserializer=sched__pb2.SchedReply.FromString,
                )
        self.ExecuteStream = channel.stream_unary(
                '/sched.Executor/ExecuteStream',
                request_serializer=sched__pb2.SchedRequest.SerializeToString,
                response_deserializer=sched__pb2.SchedReply.FromString,
                )


class ExecutorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Execute(self, request, context):
        """Remote execution via RPC call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=sched__pb2.SchedRequest.FromString,
                    response_serializer=sched__pb2.SchedReply.SerializeToString,
            ),
            'ExecuteStream': grpc.stream_unary_rpc_method_handler(
                    servicer.ExecuteStream,
                    request_deserializer=sched__pb2.SchedRequest.FromString,
                    response_serializer=sched__pb2.SchedReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sched.Executor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Executor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sched.Executor/Execute',
            sched__pb2.SchedRequest.SerializeToString,
            sched__pb2.SchedReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/sched.Executor/ExecuteStream',
            sched__pb2.SchedRequest.SerializeToString,
            sched__pb2.SchedReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
