# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prompt.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cprompt.proto\x12\x06prompt\" \n\rPromptRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"r\n\x0bPromptReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1a\n\x12\x64urationInMicroSec\x18\x02 \x01(\r\x12\x1c\n\x14gpuMemoryInMebiBytes\x18\x03 \x01(\r\x12\x18\n\x0cpromptTensor\x18\x04 \x03(\x02\x42\x02\x10\x01\x32\x43\n\x08\x45xecutor\x12\x37\n\x07\x45xecute\x12\x15.prompt.PromptRequest\x1a\x13.prompt.PromptReply\"\x00\x42\x19Z\x17promptproto/promptprotob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prompt_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\027promptproto/promptproto'
  _PROMPTREPLY.fields_by_name['promptTensor']._options = None
  _PROMPTREPLY.fields_by_name['promptTensor']._serialized_options = b'\020\001'
  _globals['_PROMPTREQUEST']._serialized_start=24
  _globals['_PROMPTREQUEST']._serialized_end=56
  _globals['_PROMPTREPLY']._serialized_start=58
  _globals['_PROMPTREPLY']._serialized_end=172
  _globals['_EXECUTOR']._serialized_start=174
  _globals['_EXECUTOR']._serialized_end=241
# @@protoc_insertion_point(module_scope)
