//
// Set up:
// $ go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
// $ go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
//
// Add `<GOPATH>/bin` to your $PATH:
// OR (!suboptimal since it overwrites $PATH by appending an additional
// line as opposed to change it directly)
// $ echo "export PATH=$PATH:$(go env GOPATH)/bin" >> ~/.profile
// $ source ~/.profile
// OR temporarily
// $ export PATH="$PATH:$(go env GOPATH)/bin"

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: prompt.proto

package promptproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PromptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // Text message field.
}

func (x *PromptRequest) Reset() {
	*x = PromptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prompt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRequest) ProtoMessage() {}

func (x *PromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prompt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRequest.ProtoReflect.Descriptor instead.
func (*PromptRequest) Descriptor() ([]byte, []int) {
	return file_prompt_proto_rawDescGZIP(), []int{0}
}

func (x *PromptRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PromptReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message              string    `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                            // Text message field.
	DurationInMicroSec   uint32    `protobuf:"varint,2,opt,name=durationInMicroSec,proto3" json:"durationInMicroSec,omitempty"`     // Execution latency [µs].
	GpuMemoryInMebiBytes uint32    `protobuf:"varint,3,opt,name=gpuMemoryInMebiBytes,proto3" json:"gpuMemoryInMebiBytes,omitempty"` // Memory usage [MiB].
	PromptTensor         []float32 `protobuf:"fixed32,4,rep,packed,name=promptTensor,proto3" json:"promptTensor,omitempty"`         // prompt gradients
}

func (x *PromptReply) Reset() {
	*x = PromptReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prompt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PromptReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptReply) ProtoMessage() {}

func (x *PromptReply) ProtoReflect() protoreflect.Message {
	mi := &file_prompt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptReply.ProtoReflect.Descriptor instead.
func (*PromptReply) Descriptor() ([]byte, []int) {
	return file_prompt_proto_rawDescGZIP(), []int{1}
}

func (x *PromptReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PromptReply) GetDurationInMicroSec() uint32 {
	if x != nil {
		return x.DurationInMicroSec
	}
	return 0
}

func (x *PromptReply) GetGpuMemoryInMebiBytes() uint32 {
	if x != nil {
		return x.GpuMemoryInMebiBytes
	}
	return 0
}

func (x *PromptReply) GetPromptTensor() []float32 {
	if x != nil {
		return x.PromptTensor
	}
	return nil
}

var File_prompt_proto protoreflect.FileDescriptor

var file_prompt_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x22, 0x29, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0xb3, 0x01, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x53, 0x65,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x12, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x53, 0x65, 0x63, 0x12, 0x32, 0x0a, 0x14, 0x67,
	0x70, 0x75, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x4d, 0x65, 0x62, 0x69, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x14, 0x67, 0x70, 0x75, 0x4d, 0x65,
	0x6d, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x4d, 0x65, 0x62, 0x69, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12,
	0x26, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x02, 0x42, 0x02, 0x10, 0x01, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x6d, 0x70,
	0x74, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x32, 0x43, 0x0a, 0x08, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x6f, 0x72, 0x12, 0x37, 0x0a, 0x07, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x12, 0x15,
	0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2e, 0x50,
	0x72, 0x6f, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x19, 0x5a, 0x17,
	0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x6d,
	0x70, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_prompt_proto_rawDescOnce sync.Once
	file_prompt_proto_rawDescData = file_prompt_proto_rawDesc
)

func file_prompt_proto_rawDescGZIP() []byte {
	file_prompt_proto_rawDescOnce.Do(func() {
		file_prompt_proto_rawDescData = protoimpl.X.CompressGZIP(file_prompt_proto_rawDescData)
	})
	return file_prompt_proto_rawDescData
}

var file_prompt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_prompt_proto_goTypes = []interface{}{
	(*PromptRequest)(nil), // 0: prompt.PromptRequest
	(*PromptReply)(nil),   // 1: prompt.PromptReply
}
var file_prompt_proto_depIdxs = []int32{
	0, // 0: prompt.Executor.Execute:input_type -> prompt.PromptRequest
	1, // 1: prompt.Executor.Execute:output_type -> prompt.PromptReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_prompt_proto_init() }
func file_prompt_proto_init() {
	if File_prompt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_prompt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PromptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prompt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PromptReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_prompt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prompt_proto_goTypes,
		DependencyIndexes: file_prompt_proto_depIdxs,
		MessageInfos:      file_prompt_proto_msgTypes,
	}.Build()
	File_prompt_proto = out.File
	file_prompt_proto_rawDesc = nil
	file_prompt_proto_goTypes = nil
	file_prompt_proto_depIdxs = nil
}
