# syntax=docker/dockerfile:1.2.x

# Stage 0: Build #
# Use the official Golang image to create a build artifact.
# This is based on Debian and sets the GOPATH to /go.
FROM golang:1.17 as BUILDER

# Create and change to the app directory.
WORKDIR /app

# Retrieve application dependencies using go modules.
# Allows container builds to reuse downloaded dependencies.
COPY go.* ./
RUN go mod download

# Copy local code to the container image.
COPY * ./

# -mod=readonly: ensures immutable go.mod and go.sum in container builds.
# CGO_ENABLED=1: uses common libraries found on most major OS distributions.
# GOARCH=amd64 GOGCCFLAGS=-m64: specifies x86, 64-bit GCC.
RUN CGO_ENABLED=1 GOARCH=amd64 GOGCCFLAGS=-m64 GOOS=linux go build -mod=readonly -v -o test-server

# Stage 1: Run #
# Use Debain slim, which turns out to be smaller.
FROM debian:stable-slim
# Add the following if Alpine is used 
# RUN apk add --no-cache libc6-compat 

# Copy the binary to the production image from the BUILDER stage.
COPY --from=BUILDER /app/test-server /test-server

# Run the web service on container startup.
CMD ["/test-server"]