# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pkg/workload/proto/faas.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pkg/workload/proto/faas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dpkg/workload/proto/faas.proto\x12\x04\x66\x61\x61s\"T\n\x0b\x46\x61\x61sRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x19\n\x11runtimeInMilliSec\x18\x02 \x01(\r\x12\x19\n\x11memoryInMebiBytes\x18\x03 \x01(\r\"Q\n\tFaasReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1a\n\x12\x64urationInMicroSec\x18\x02 \x01(\r\x12\x17\n\x0fmemoryUsageInKb\x18\x03 \x01(\r2;\n\x08\x45xecutor\x12/\n\x07\x45xecute\x12\x11.faas.FaasRequest\x1a\x0f.faas.FaasReply\"\x00\x42\x33Z1github.com/vhive-serverless/loader/workload/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pkg.workload.proto.faas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/vhive-serverless/loader/workload/proto'
  _globals['_FAASREQUEST']._serialized_start=39
  _globals['_FAASREQUEST']._serialized_end=123
  _globals['_FAASREPLY']._serialized_start=125
  _globals['_FAASREPLY']._serialized_end=206
  _globals['_EXECUTOR']._serialized_start=208
  _globals['_EXECUTOR']._serialized_end=267
# @@protoc_insertion_point(module_scope)
