//
// Set up:
// $ go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
// $ go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
//
// Add `<GOPATH>/bin` to your $PATH:
// OR (!suboptimal since it overwrites $PATH by appending an additional
// line as opposed to change it directly)
// $ echo "export PATH=$PATH:$(go env GOPATH)/bin" >> ~/.profile
// $ source ~/.profile
// OR temporarily
// $ export PATH="$PATH:$(go env GOPATH)/bin"

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.19.4
// source: pkg/workload/proto/faas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FaasRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Message           string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                      // Text message field (unused).
	RuntimeInMilliSec uint32                 `protobuf:"varint,2,opt,name=runtimeInMilliSec,proto3" json:"runtimeInMilliSec,omitempty"` // Execution runtime [ms].
	MemoryInMebiBytes uint32                 `protobuf:"varint,3,opt,name=memoryInMebiBytes,proto3" json:"memoryInMebiBytes,omitempty"` // Request memory usage [MiB].
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FaasRequest) Reset() {
	*x = FaasRequest{}
	mi := &file_pkg_workload_proto_faas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaasRequest) ProtoMessage() {}

func (x *FaasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workload_proto_faas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaasRequest.ProtoReflect.Descriptor instead.
func (*FaasRequest) Descriptor() ([]byte, []int) {
	return file_pkg_workload_proto_faas_proto_rawDescGZIP(), []int{0}
}

func (x *FaasRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FaasRequest) GetRuntimeInMilliSec() uint32 {
	if x != nil {
		return x.RuntimeInMilliSec
	}
	return 0
}

func (x *FaasRequest) GetMemoryInMebiBytes() uint32 {
	if x != nil {
		return x.MemoryInMebiBytes
	}
	return 0
}

type FaasReply struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Message            string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                        // Text message field (unused).
	DurationInMicroSec uint32                 `protobuf:"varint,2,opt,name=durationInMicroSec,proto3" json:"durationInMicroSec,omitempty"` // Execution latency [µs].
	MemoryUsageInKb    uint32                 `protobuf:"varint,3,opt,name=memoryUsageInKb,proto3" json:"memoryUsageInKb,omitempty"`       // Memory usage [KB].
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FaasReply) Reset() {
	*x = FaasReply{}
	mi := &file_pkg_workload_proto_faas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaasReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaasReply) ProtoMessage() {}

func (x *FaasReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workload_proto_faas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaasReply.ProtoReflect.Descriptor instead.
func (*FaasReply) Descriptor() ([]byte, []int) {
	return file_pkg_workload_proto_faas_proto_rawDescGZIP(), []int{1}
}

func (x *FaasReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FaasReply) GetDurationInMicroSec() uint32 {
	if x != nil {
		return x.DurationInMicroSec
	}
	return 0
}

func (x *FaasReply) GetMemoryUsageInKb() uint32 {
	if x != nil {
		return x.MemoryUsageInKb
	}
	return 0
}

var File_pkg_workload_proto_faas_proto protoreflect.FileDescriptor

const file_pkg_workload_proto_faas_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/workload/proto/faas.proto\x12\x04faas\"\x83\x01\n" +
	"\vFaasRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12,\n" +
	"\x11runtimeInMilliSec\x18\x02 \x01(\rR\x11runtimeInMilliSec\x12,\n" +
	"\x11memoryInMebiBytes\x18\x03 \x01(\rR\x11memoryInMebiBytes\"\x7f\n" +
	"\tFaasReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12.\n" +
	"\x12durationInMicroSec\x18\x02 \x01(\rR\x12durationInMicroSec\x12(\n" +
	"\x0fmemoryUsageInKb\x18\x03 \x01(\rR\x0fmemoryUsageInKb2;\n" +
	"\bExecutor\x12/\n" +
	"\aExecute\x12\x11.faas.FaasRequest\x1a\x0f.faas.FaasReply\"\x00B3Z1github.com/vhive-serverless/loader/workload/protob\x06proto3"

var (
	file_pkg_workload_proto_faas_proto_rawDescOnce sync.Once
	file_pkg_workload_proto_faas_proto_rawDescData []byte
)

func file_pkg_workload_proto_faas_proto_rawDescGZIP() []byte {
	file_pkg_workload_proto_faas_proto_rawDescOnce.Do(func() {
		file_pkg_workload_proto_faas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_workload_proto_faas_proto_rawDesc), len(file_pkg_workload_proto_faas_proto_rawDesc)))
	})
	return file_pkg_workload_proto_faas_proto_rawDescData
}

var file_pkg_workload_proto_faas_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_workload_proto_faas_proto_goTypes = []any{
	(*FaasRequest)(nil), // 0: faas.FaasRequest
	(*FaasReply)(nil),   // 1: faas.FaasReply
}
var file_pkg_workload_proto_faas_proto_depIdxs = []int32{
	0, // 0: faas.Executor.Execute:input_type -> faas.FaasRequest
	1, // 1: faas.Executor.Execute:output_type -> faas.FaasReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_workload_proto_faas_proto_init() }
func file_pkg_workload_proto_faas_proto_init() {
	if File_pkg_workload_proto_faas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_workload_proto_faas_proto_rawDesc), len(file_pkg_workload_proto_faas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_workload_proto_faas_proto_goTypes,
		DependencyIndexes: file_pkg_workload_proto_faas_proto_depIdxs,
		MessageInfos:      file_pkg_workload_proto_faas_proto_msgTypes,
	}.Build()
	File_pkg_workload_proto_faas_proto = out.File
	file_pkg_workload_proto_faas_proto_goTypes = nil
	file_pkg_workload_proto_faas_proto_depIdxs = nil
}
