// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.19.4
// source: pkg/workload/proto/hardware_manager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CorePool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CoreList      []uint32               `protobuf:"varint,2,rep,packed,name=core_list,json=coreList,proto3" json:"core_list,omitempty"`
	CoreFreq      []uint32               `protobuf:"varint,3,rep,packed,name=core_freq,json=coreFreq,proto3" json:"core_freq,omitempty"`
	ReuseCgroup   bool                   `protobuf:"varint,4,opt,name=reuse_cgroup,json=reuseCgroup,proto3" json:"reuse_cgroup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorePool) Reset() {
	*x = CorePool{}
	mi := &file_pkg_workload_proto_hardware_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorePool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorePool) ProtoMessage() {}

func (x *CorePool) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workload_proto_hardware_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorePool.ProtoReflect.Descriptor instead.
func (*CorePool) Descriptor() ([]byte, []int) {
	return file_pkg_workload_proto_hardware_manager_proto_rawDescGZIP(), []int{0}
}

func (x *CorePool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CorePool) GetCoreList() []uint32 {
	if x != nil {
		return x.CoreList
	}
	return nil
}

func (x *CorePool) GetCoreFreq() []uint32 {
	if x != nil {
		return x.CoreFreq
	}
	return nil
}

func (x *CorePool) GetReuseCgroup() bool {
	if x != nil {
		return x.ReuseCgroup
	}
	return false
}

type CorePoolName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorePoolName) Reset() {
	*x = CorePoolName{}
	mi := &file_pkg_workload_proto_hardware_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorePoolName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorePoolName) ProtoMessage() {}

func (x *CorePoolName) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workload_proto_hardware_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorePoolName.ProtoReflect.Descriptor instead.
func (*CorePoolName) Descriptor() ([]byte, []int) {
	return file_pkg_workload_proto_hardware_manager_proto_rawDescGZIP(), []int{1}
}

func (x *CorePoolName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pkg_workload_proto_hardware_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workload_proto_hardware_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_workload_proto_hardware_manager_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddPIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pid           []uint32               `protobuf:"varint,2,rep,packed,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPIDReq) Reset() {
	*x = AddPIDReq{}
	mi := &file_pkg_workload_proto_hardware_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPIDReq) ProtoMessage() {}

func (x *AddPIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workload_proto_hardware_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPIDReq.ProtoReflect.Descriptor instead.
func (*AddPIDReq) Descriptor() ([]byte, []int) {
	return file_pkg_workload_proto_hardware_manager_proto_rawDescGZIP(), []int{3}
}

func (x *AddPIDReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddPIDReq) GetPid() []uint32 {
	if x != nil {
		return x.Pid
	}
	return nil
}

type CoreUtilization struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AverageUtilization float64                `protobuf:"fixed64,1,opt,name=average_utilization,json=averageUtilization,proto3" json:"average_utilization,omitempty"`
	CoreUtilization    []float64              `protobuf:"fixed64,2,rep,packed,name=core_utilization,json=coreUtilization,proto3" json:"core_utilization,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CoreUtilization) Reset() {
	*x = CoreUtilization{}
	mi := &file_pkg_workload_proto_hardware_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreUtilization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreUtilization) ProtoMessage() {}

func (x *CoreUtilization) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workload_proto_hardware_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreUtilization.ProtoReflect.Descriptor instead.
func (*CoreUtilization) Descriptor() ([]byte, []int) {
	return file_pkg_workload_proto_hardware_manager_proto_rawDescGZIP(), []int{4}
}

func (x *CoreUtilization) GetAverageUtilization() float64 {
	if x != nil {
		return x.AverageUtilization
	}
	return 0
}

func (x *CoreUtilization) GetCoreUtilization() []float64 {
	if x != nil {
		return x.CoreUtilization
	}
	return nil
}

type PkgPower struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalPower    float64                `protobuf:"fixed64,1,opt,name=total_power,json=totalPower,proto3" json:"total_power,omitempty"`
	PkgPower      []float64              `protobuf:"fixed64,2,rep,packed,name=pkg_power,json=pkgPower,proto3" json:"pkg_power,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PkgPower) Reset() {
	*x = PkgPower{}
	mi := &file_pkg_workload_proto_hardware_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PkgPower) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PkgPower) ProtoMessage() {}

func (x *PkgPower) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workload_proto_hardware_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PkgPower.ProtoReflect.Descriptor instead.
func (*PkgPower) Descriptor() ([]byte, []int) {
	return file_pkg_workload_proto_hardware_manager_proto_rawDescGZIP(), []int{5}
}

func (x *PkgPower) GetTotalPower() float64 {
	if x != nil {
		return x.TotalPower
	}
	return 0
}

func (x *PkgPower) GetPkgPower() []float64 {
	if x != nil {
		return x.PkgPower
	}
	return nil
}

type MemoryStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalMemory   float64                `protobuf:"fixed64,1,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`
	UsedMemory    float64                `protobuf:"fixed64,2,opt,name=used_memory,json=usedMemory,proto3" json:"used_memory,omitempty"`
	FreeMemory    float64                `protobuf:"fixed64,3,opt,name=free_memory,json=freeMemory,proto3" json:"free_memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryStatus) Reset() {
	*x = MemoryStatus{}
	mi := &file_pkg_workload_proto_hardware_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryStatus) ProtoMessage() {}

func (x *MemoryStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workload_proto_hardware_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryStatus.ProtoReflect.Descriptor instead.
func (*MemoryStatus) Descriptor() ([]byte, []int) {
	return file_pkg_workload_proto_hardware_manager_proto_rawDescGZIP(), []int{6}
}

func (x *MemoryStatus) GetTotalMemory() float64 {
	if x != nil {
		return x.TotalMemory
	}
	return 0
}

func (x *MemoryStatus) GetUsedMemory() float64 {
	if x != nil {
		return x.UsedMemory
	}
	return 0
}

func (x *MemoryStatus) GetFreeMemory() float64 {
	if x != nil {
		return x.FreeMemory
	}
	return 0
}

type CoreFrequency struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AverageFrequency float64                `protobuf:"fixed64,1,opt,name=average_frequency,json=averageFrequency,proto3" json:"average_frequency,omitempty"`
	CoreFrequency    []float64              `protobuf:"fixed64,2,rep,packed,name=core_frequency,json=coreFrequency,proto3" json:"core_frequency,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CoreFrequency) Reset() {
	*x = CoreFrequency{}
	mi := &file_pkg_workload_proto_hardware_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreFrequency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreFrequency) ProtoMessage() {}

func (x *CoreFrequency) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workload_proto_hardware_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreFrequency.ProtoReflect.Descriptor instead.
func (*CoreFrequency) Descriptor() ([]byte, []int) {
	return file_pkg_workload_proto_hardware_manager_proto_rawDescGZIP(), []int{7}
}

func (x *CoreFrequency) GetAverageFrequency() float64 {
	if x != nil {
		return x.AverageFrequency
	}
	return 0
}

func (x *CoreFrequency) GetCoreFrequency() []float64 {
	if x != nil {
		return x.CoreFrequency
	}
	return nil
}

type CgroupCPUTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UsageTotal    float64                `protobuf:"fixed64,2,opt,name=usage_total,json=usageTotal,proto3" json:"usage_total,omitempty"`    // Total CPU time used by the cgroup
	UsageUser     float64                `protobuf:"fixed64,3,opt,name=usage_user,json=usageUser,proto3" json:"usage_user,omitempty"`       // User CPU time used by the cgroup
	UsageSystem   float64                `protobuf:"fixed64,4,opt,name=usage_system,json=usageSystem,proto3" json:"usage_system,omitempty"` // System CPU time used by the cgroup
	PressureSome  float64                `protobuf:"fixed64,5,opt,name=pressure_some,json=pressureSome,proto3" json:"pressure_some,omitempty"`
	PressureFull  float64                `protobuf:"fixed64,6,opt,name=pressure_full,json=pressureFull,proto3" json:"pressure_full,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CgroupCPUTime) Reset() {
	*x = CgroupCPUTime{}
	mi := &file_pkg_workload_proto_hardware_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CgroupCPUTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CgroupCPUTime) ProtoMessage() {}

func (x *CgroupCPUTime) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workload_proto_hardware_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CgroupCPUTime.ProtoReflect.Descriptor instead.
func (*CgroupCPUTime) Descriptor() ([]byte, []int) {
	return file_pkg_workload_proto_hardware_manager_proto_rawDescGZIP(), []int{8}
}

func (x *CgroupCPUTime) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CgroupCPUTime) GetUsageTotal() float64 {
	if x != nil {
		return x.UsageTotal
	}
	return 0
}

func (x *CgroupCPUTime) GetUsageUser() float64 {
	if x != nil {
		return x.UsageUser
	}
	return 0
}

func (x *CgroupCPUTime) GetUsageSystem() float64 {
	if x != nil {
		return x.UsageSystem
	}
	return 0
}

func (x *CgroupCPUTime) GetPressureSome() float64 {
	if x != nil {
		return x.PressureSome
	}
	return 0
}

func (x *CgroupCPUTime) GetPressureFull() float64 {
	if x != nil {
		return x.PressureFull
	}
	return 0
}

type NodeStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CoreUtilization *CoreUtilization       `protobuf:"bytes,1,opt,name=core_utilization,json=coreUtilization,proto3" json:"core_utilization,omitempty"`
	PkgPower        *PkgPower              `protobuf:"bytes,2,opt,name=pkg_power,json=pkgPower,proto3" json:"pkg_power,omitempty"`
	MemoryStatus    *MemoryStatus          `protobuf:"bytes,3,opt,name=memory_status,json=memoryStatus,proto3" json:"memory_status,omitempty"`
	CoreFrequency   *CoreFrequency         `protobuf:"bytes,4,opt,name=core_frequency,json=coreFrequency,proto3" json:"core_frequency,omitempty"`
	CorePools       []*CorePool            `protobuf:"bytes,5,rep,name=core_pools,json=corePools,proto3" json:"core_pools,omitempty"`
	CgroupCpuTimes  []*CgroupCPUTime       `protobuf:"bytes,6,rep,name=cgroup_cpu_times,json=cgroupCpuTimes,proto3" json:"cgroup_cpu_times,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_pkg_workload_proto_hardware_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workload_proto_hardware_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_pkg_workload_proto_hardware_manager_proto_rawDescGZIP(), []int{9}
}

func (x *NodeStatus) GetCoreUtilization() *CoreUtilization {
	if x != nil {
		return x.CoreUtilization
	}
	return nil
}

func (x *NodeStatus) GetPkgPower() *PkgPower {
	if x != nil {
		return x.PkgPower
	}
	return nil
}

func (x *NodeStatus) GetMemoryStatus() *MemoryStatus {
	if x != nil {
		return x.MemoryStatus
	}
	return nil
}

func (x *NodeStatus) GetCoreFrequency() *CoreFrequency {
	if x != nil {
		return x.CoreFrequency
	}
	return nil
}

func (x *NodeStatus) GetCorePools() []*CorePool {
	if x != nil {
		return x.CorePools
	}
	return nil
}

func (x *NodeStatus) GetCgroupCpuTimes() []*CgroupCPUTime {
	if x != nil {
		return x.CgroupCpuTimes
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_workload_proto_hardware_manager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workload_proto_hardware_manager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_workload_proto_hardware_manager_proto_rawDescGZIP(), []int{10}
}

var File_pkg_workload_proto_hardware_manager_proto protoreflect.FileDescriptor

const file_pkg_workload_proto_hardware_manager_proto_rawDesc = "" +
	"\n" +
	")pkg/workload/proto/hardware_manager.proto\x12\x05proto\"{\n" +
	"\bCorePool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tcore_list\x18\x02 \x03(\rR\bcoreList\x12\x1b\n" +
	"\tcore_freq\x18\x03 \x03(\rR\bcoreFreq\x12!\n" +
	"\freuse_cgroup\x18\x04 \x01(\bR\vreuseCgroup\"\"\n" +
	"\fCorePoolName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"$\n" +
	"\bResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"1\n" +
	"\tAddPIDReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03pid\x18\x02 \x03(\rR\x03pid\"m\n" +
	"\x0fCoreUtilization\x12/\n" +
	"\x13average_utilization\x18\x01 \x01(\x01R\x12averageUtilization\x12)\n" +
	"\x10core_utilization\x18\x02 \x03(\x01R\x0fcoreUtilization\"H\n" +
	"\bPkgPower\x12\x1f\n" +
	"\vtotal_power\x18\x01 \x01(\x01R\n" +
	"totalPower\x12\x1b\n" +
	"\tpkg_power\x18\x02 \x03(\x01R\bpkgPower\"s\n" +
	"\fMemoryStatus\x12!\n" +
	"\ftotal_memory\x18\x01 \x01(\x01R\vtotalMemory\x12\x1f\n" +
	"\vused_memory\x18\x02 \x01(\x01R\n" +
	"usedMemory\x12\x1f\n" +
	"\vfree_memory\x18\x03 \x01(\x01R\n" +
	"freeMemory\"c\n" +
	"\rCoreFrequency\x12+\n" +
	"\x11average_frequency\x18\x01 \x01(\x01R\x10averageFrequency\x12%\n" +
	"\x0ecore_frequency\x18\x02 \x03(\x01R\rcoreFrequency\"\xd0\x01\n" +
	"\rCgroupCPUTime\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vusage_total\x18\x02 \x01(\x01R\n" +
	"usageTotal\x12\x1d\n" +
	"\n" +
	"usage_user\x18\x03 \x01(\x01R\tusageUser\x12!\n" +
	"\fusage_system\x18\x04 \x01(\x01R\vusageSystem\x12#\n" +
	"\rpressure_some\x18\x05 \x01(\x01R\fpressureSome\x12#\n" +
	"\rpressure_full\x18\x06 \x01(\x01R\fpressureFull\"\xe4\x02\n" +
	"\n" +
	"NodeStatus\x12A\n" +
	"\x10core_utilization\x18\x01 \x01(\v2\x16.proto.CoreUtilizationR\x0fcoreUtilization\x12,\n" +
	"\tpkg_power\x18\x02 \x01(\v2\x0f.proto.PkgPowerR\bpkgPower\x128\n" +
	"\rmemory_status\x18\x03 \x01(\v2\x13.proto.MemoryStatusR\fmemoryStatus\x12;\n" +
	"\x0ecore_frequency\x18\x04 \x01(\v2\x14.proto.CoreFrequencyR\rcoreFrequency\x12.\n" +
	"\n" +
	"core_pools\x18\x05 \x03(\v2\x0f.proto.CorePoolR\tcorePools\x12>\n" +
	"\x10cgroup_cpu_times\x18\x06 \x03(\v2\x14.proto.CgroupCPUTimeR\x0ecgroupCpuTimes\"\a\n" +
	"\x05Empty2\x8f\x02\n" +
	"\x0fHardwareManager\x12/\n" +
	"\vSetCorePool\x12\x0f.proto.CorePool\x1a\x0f.proto.Response\x122\n" +
	"\x0eUpdateCorePool\x12\x0f.proto.CorePool\x1a\x0f.proto.Response\x127\n" +
	"\x0fDestroyCorePool\x12\x13.proto.CorePoolName\x1a\x0f.proto.Response\x121\n" +
	"\x0eGetNodeMetrics\x12\f.proto.Empty\x1a\x11.proto.NodeStatus\x12+\n" +
	"\x06AddPID\x12\x10.proto.AddPIDReq\x1a\x0f.proto.ResponseB+Z)github.com/JooyoungPark73/khala/pkg/protob\x06proto3"

var (
	file_pkg_workload_proto_hardware_manager_proto_rawDescOnce sync.Once
	file_pkg_workload_proto_hardware_manager_proto_rawDescData []byte
)

func file_pkg_workload_proto_hardware_manager_proto_rawDescGZIP() []byte {
	file_pkg_workload_proto_hardware_manager_proto_rawDescOnce.Do(func() {
		file_pkg_workload_proto_hardware_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_workload_proto_hardware_manager_proto_rawDesc), len(file_pkg_workload_proto_hardware_manager_proto_rawDesc)))
	})
	return file_pkg_workload_proto_hardware_manager_proto_rawDescData
}

var file_pkg_workload_proto_hardware_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_workload_proto_hardware_manager_proto_goTypes = []any{
	(*CorePool)(nil),        // 0: proto.CorePool
	(*CorePoolName)(nil),    // 1: proto.CorePoolName
	(*Response)(nil),        // 2: proto.Response
	(*AddPIDReq)(nil),       // 3: proto.AddPIDReq
	(*CoreUtilization)(nil), // 4: proto.CoreUtilization
	(*PkgPower)(nil),        // 5: proto.PkgPower
	(*MemoryStatus)(nil),    // 6: proto.MemoryStatus
	(*CoreFrequency)(nil),   // 7: proto.CoreFrequency
	(*CgroupCPUTime)(nil),   // 8: proto.CgroupCPUTime
	(*NodeStatus)(nil),      // 9: proto.NodeStatus
	(*Empty)(nil),           // 10: proto.Empty
}
var file_pkg_workload_proto_hardware_manager_proto_depIdxs = []int32{
	4,  // 0: proto.NodeStatus.core_utilization:type_name -> proto.CoreUtilization
	5,  // 1: proto.NodeStatus.pkg_power:type_name -> proto.PkgPower
	6,  // 2: proto.NodeStatus.memory_status:type_name -> proto.MemoryStatus
	7,  // 3: proto.NodeStatus.core_frequency:type_name -> proto.CoreFrequency
	0,  // 4: proto.NodeStatus.core_pools:type_name -> proto.CorePool
	8,  // 5: proto.NodeStatus.cgroup_cpu_times:type_name -> proto.CgroupCPUTime
	0,  // 6: proto.HardwareManager.SetCorePool:input_type -> proto.CorePool
	0,  // 7: proto.HardwareManager.UpdateCorePool:input_type -> proto.CorePool
	1,  // 8: proto.HardwareManager.DestroyCorePool:input_type -> proto.CorePoolName
	10, // 9: proto.HardwareManager.GetNodeMetrics:input_type -> proto.Empty
	3,  // 10: proto.HardwareManager.AddPID:input_type -> proto.AddPIDReq
	2,  // 11: proto.HardwareManager.SetCorePool:output_type -> proto.Response
	2,  // 12: proto.HardwareManager.UpdateCorePool:output_type -> proto.Response
	2,  // 13: proto.HardwareManager.DestroyCorePool:output_type -> proto.Response
	9,  // 14: proto.HardwareManager.GetNodeMetrics:output_type -> proto.NodeStatus
	2,  // 15: proto.HardwareManager.AddPID:output_type -> proto.Response
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_workload_proto_hardware_manager_proto_init() }
func file_pkg_workload_proto_hardware_manager_proto_init() {
	if File_pkg_workload_proto_hardware_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_workload_proto_hardware_manager_proto_rawDesc), len(file_pkg_workload_proto_hardware_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_workload_proto_hardware_manager_proto_goTypes,
		DependencyIndexes: file_pkg_workload_proto_hardware_manager_proto_depIdxs,
		MessageInfos:      file_pkg_workload_proto_hardware_manager_proto_msgTypes,
	}.Build()
	File_pkg_workload_proto_hardware_manager_proto = out.File
	file_pkg_workload_proto_hardware_manager_proto_goTypes = nil
	file_pkg_workload_proto_hardware_manager_proto_depIdxs = nil
}
