// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: pkg/workload/proto/hardware_manager.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HardwareManager_SetCorePool_FullMethodName     = "/proto.HardwareManager/SetCorePool"
	HardwareManager_UpdateCorePool_FullMethodName  = "/proto.HardwareManager/UpdateCorePool"
	HardwareManager_DestroyCorePool_FullMethodName = "/proto.HardwareManager/DestroyCorePool"
	HardwareManager_GetNodeMetrics_FullMethodName  = "/proto.HardwareManager/GetNodeMetrics"
	HardwareManager_AddPID_FullMethodName          = "/proto.HardwareManager/AddPID"
)

// HardwareManagerClient is the client API for HardwareManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HardwareManagerClient interface {
	SetCorePool(ctx context.Context, in *CorePool, opts ...grpc.CallOption) (*Response, error)
	UpdateCorePool(ctx context.Context, in *CorePool, opts ...grpc.CallOption) (*Response, error)
	DestroyCorePool(ctx context.Context, in *CorePoolName, opts ...grpc.CallOption) (*Response, error)
	GetNodeMetrics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeStatus, error)
	AddPID(ctx context.Context, in *AddPIDReq, opts ...grpc.CallOption) (*Response, error)
}

type hardwareManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewHardwareManagerClient(cc grpc.ClientConnInterface) HardwareManagerClient {
	return &hardwareManagerClient{cc}
}

func (c *hardwareManagerClient) SetCorePool(ctx context.Context, in *CorePool, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, HardwareManager_SetCorePool_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hardwareManagerClient) UpdateCorePool(ctx context.Context, in *CorePool, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, HardwareManager_UpdateCorePool_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hardwareManagerClient) DestroyCorePool(ctx context.Context, in *CorePoolName, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, HardwareManager_DestroyCorePool_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hardwareManagerClient) GetNodeMetrics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeStatus, error) {
	out := new(NodeStatus)
	err := c.cc.Invoke(ctx, HardwareManager_GetNodeMetrics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hardwareManagerClient) AddPID(ctx context.Context, in *AddPIDReq, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, HardwareManager_AddPID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HardwareManagerServer is the server API for HardwareManager service.
// All implementations must embed UnimplementedHardwareManagerServer
// for forward compatibility
type HardwareManagerServer interface {
	SetCorePool(context.Context, *CorePool) (*Response, error)
	UpdateCorePool(context.Context, *CorePool) (*Response, error)
	DestroyCorePool(context.Context, *CorePoolName) (*Response, error)
	GetNodeMetrics(context.Context, *Empty) (*NodeStatus, error)
	AddPID(context.Context, *AddPIDReq) (*Response, error)
	mustEmbedUnimplementedHardwareManagerServer()
}

// UnimplementedHardwareManagerServer must be embedded to have forward compatible implementations.
type UnimplementedHardwareManagerServer struct {
}

func (UnimplementedHardwareManagerServer) SetCorePool(context.Context, *CorePool) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCorePool not implemented")
}
func (UnimplementedHardwareManagerServer) UpdateCorePool(context.Context, *CorePool) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCorePool not implemented")
}
func (UnimplementedHardwareManagerServer) DestroyCorePool(context.Context, *CorePoolName) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyCorePool not implemented")
}
func (UnimplementedHardwareManagerServer) GetNodeMetrics(context.Context, *Empty) (*NodeStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeMetrics not implemented")
}
func (UnimplementedHardwareManagerServer) AddPID(context.Context, *AddPIDReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPID not implemented")
}
func (UnimplementedHardwareManagerServer) mustEmbedUnimplementedHardwareManagerServer() {}

// UnsafeHardwareManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HardwareManagerServer will
// result in compilation errors.
type UnsafeHardwareManagerServer interface {
	mustEmbedUnimplementedHardwareManagerServer()
}

func RegisterHardwareManagerServer(s grpc.ServiceRegistrar, srv HardwareManagerServer) {
	s.RegisterService(&HardwareManager_ServiceDesc, srv)
}

func _HardwareManager_SetCorePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CorePool)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HardwareManagerServer).SetCorePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HardwareManager_SetCorePool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HardwareManagerServer).SetCorePool(ctx, req.(*CorePool))
	}
	return interceptor(ctx, in, info, handler)
}

func _HardwareManager_UpdateCorePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CorePool)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HardwareManagerServer).UpdateCorePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HardwareManager_UpdateCorePool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HardwareManagerServer).UpdateCorePool(ctx, req.(*CorePool))
	}
	return interceptor(ctx, in, info, handler)
}

func _HardwareManager_DestroyCorePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CorePoolName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HardwareManagerServer).DestroyCorePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HardwareManager_DestroyCorePool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HardwareManagerServer).DestroyCorePool(ctx, req.(*CorePoolName))
	}
	return interceptor(ctx, in, info, handler)
}

func _HardwareManager_GetNodeMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HardwareManagerServer).GetNodeMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HardwareManager_GetNodeMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HardwareManagerServer).GetNodeMetrics(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HardwareManager_AddPID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HardwareManagerServer).AddPID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HardwareManager_AddPID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HardwareManagerServer).AddPID(ctx, req.(*AddPIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

// HardwareManager_ServiceDesc is the grpc.ServiceDesc for HardwareManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HardwareManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HardwareManager",
	HandlerType: (*HardwareManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetCorePool",
			Handler:    _HardwareManager_SetCorePool_Handler,
		},
		{
			MethodName: "UpdateCorePool",
			Handler:    _HardwareManager_UpdateCorePool_Handler,
		},
		{
			MethodName: "DestroyCorePool",
			Handler:    _HardwareManager_DestroyCorePool_Handler,
		},
		{
			MethodName: "GetNodeMetrics",
			Handler:    _HardwareManager_GetNodeMetrics_Handler,
		},
		{
			MethodName: "AddPID",
			Handler:    _HardwareManager_AddPID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/workload/proto/hardware_manager.proto",
}
