// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.19.4
// source: pkg/workload/proto/knative_integration.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmName        string                 `protobuf:"bytes,1,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVMRequest) Reset() {
	*x = AddVMRequest{}
	mi := &file_pkg_workload_proto_knative_integration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVMRequest) ProtoMessage() {}

func (x *AddVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workload_proto_knative_integration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVMRequest.ProtoReflect.Descriptor instead.
func (*AddVMRequest) Descriptor() ([]byte, []int) {
	return file_pkg_workload_proto_knative_integration_proto_rawDescGZIP(), []int{0}
}

func (x *AddVMRequest) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

type AddVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	VmId          string                 `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	WorkloadName  string                 `protobuf:"bytes,3,opt,name=workload_name,json=workloadName,proto3" json:"workload_name,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	RpcPort       string                 `protobuf:"bytes,5,opt,name=rpc_port,json=rpcPort,proto3" json:"rpc_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVMResponse) Reset() {
	*x = AddVMResponse{}
	mi := &file_pkg_workload_proto_knative_integration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVMResponse) ProtoMessage() {}

func (x *AddVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workload_proto_knative_integration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVMResponse.ProtoReflect.Descriptor instead.
func (*AddVMResponse) Descriptor() ([]byte, []int) {
	return file_pkg_workload_proto_knative_integration_proto_rawDescGZIP(), []int{1}
}

func (x *AddVMResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddVMResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *AddVMResponse) GetWorkloadName() string {
	if x != nil {
		return x.WorkloadName
	}
	return ""
}

func (x *AddVMResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AddVMResponse) GetRpcPort() string {
	if x != nil {
		return x.RpcPort
	}
	return ""
}

type RemoveVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveVMRequest) Reset() {
	*x = RemoveVMRequest{}
	mi := &file_pkg_workload_proto_knative_integration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVMRequest) ProtoMessage() {}

func (x *RemoveVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workload_proto_knative_integration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVMRequest.ProtoReflect.Descriptor instead.
func (*RemoveVMRequest) Descriptor() ([]byte, []int) {
	return file_pkg_workload_proto_knative_integration_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveVMRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type RemoveVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveVMResponse) Reset() {
	*x = RemoveVMResponse{}
	mi := &file_pkg_workload_proto_knative_integration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVMResponse) ProtoMessage() {}

func (x *RemoveVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workload_proto_knative_integration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVMResponse.ProtoReflect.Descriptor instead.
func (*RemoveVMResponse) Descriptor() ([]byte, []int) {
	return file_pkg_workload_proto_knative_integration_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveVMResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveVMResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DestroyAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DestroyAll    bool                   `protobuf:"varint,1,opt,name=destroy_all,json=destroyAll,proto3" json:"destroy_all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyAllRequest) Reset() {
	*x = DestroyAllRequest{}
	mi := &file_pkg_workload_proto_knative_integration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyAllRequest) ProtoMessage() {}

func (x *DestroyAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workload_proto_knative_integration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyAllRequest.ProtoReflect.Descriptor instead.
func (*DestroyAllRequest) Descriptor() ([]byte, []int) {
	return file_pkg_workload_proto_knative_integration_proto_rawDescGZIP(), []int{4}
}

func (x *DestroyAllRequest) GetDestroyAll() bool {
	if x != nil {
		return x.DestroyAll
	}
	return false
}

type DestroyAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyAllResponse) Reset() {
	*x = DestroyAllResponse{}
	mi := &file_pkg_workload_proto_knative_integration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyAllResponse) ProtoMessage() {}

func (x *DestroyAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workload_proto_knative_integration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyAllResponse.ProtoReflect.Descriptor instead.
func (*DestroyAllResponse) Descriptor() ([]byte, []int) {
	return file_pkg_workload_proto_knative_integration_proto_rawDescGZIP(), []int{5}
}

func (x *DestroyAllResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workload      string                 `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_pkg_workload_proto_knative_integration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workload_proto_knative_integration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_pkg_workload_proto_knative_integration_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSnapshotRequest) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

type CreateSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotResponse) Reset() {
	*x = CreateSnapshotResponse{}
	mi := &file_pkg_workload_proto_knative_integration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotResponse) ProtoMessage() {}

func (x *CreateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workload_proto_knative_integration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CreateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_pkg_workload_proto_knative_integration_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSnapshotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateSnapshotResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_workload_proto_knative_integration_proto protoreflect.FileDescriptor

const file_pkg_workload_proto_knative_integration_proto_rawDesc = "" +
	"\n" +
	",pkg/workload/proto/knative_integration.proto\x12\x05proto\"'\n" +
	"\fAddVMRequest\x12\x17\n" +
	"\avm_name\x18\x01 \x01(\tR\x06vmName\"\x8e\x01\n" +
	"\rAddVMResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x13\n" +
	"\x05vm_id\x18\x02 \x01(\tR\x04vmId\x12#\n" +
	"\rworkload_name\x18\x03 \x01(\tR\fworkloadName\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x19\n" +
	"\brpc_port\x18\x05 \x01(\tR\arpcPort\"&\n" +
	"\x0fRemoveVMRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"F\n" +
	"\x10RemoveVMResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x11DestroyAllRequest\x12\x1f\n" +
	"\vdestroy_all\x18\x01 \x01(\bR\n" +
	"destroyAll\".\n" +
	"\x12DestroyAllResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\x15CreateSnapshotRequest\x12\x1a\n" +
	"\bworkload\x18\x01 \x01(\tR\bworkload\"L\n" +
	"\x16CreateSnapshotResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9c\x02\n" +
	"\x17KhalaKnativeIntegration\x122\n" +
	"\x05AddVM\x12\x13.proto.AddVMRequest\x1a\x14.proto.AddVMResponse\x12;\n" +
	"\bRemoveVM\x12\x16.proto.RemoveVMRequest\x1a\x17.proto.RemoveVMResponse\x12A\n" +
	"\n" +
	"DestroyAll\x12\x18.proto.DestroyAllRequest\x1a\x19.proto.DestroyAllResponse\x12M\n" +
	"\x0eCreateSnapshot\x12\x1c.proto.CreateSnapshotRequest\x1a\x1d.proto.CreateSnapshotResponseB+Z)github.com/JooyoungPark73/khala/pkg/protob\x06proto3"

var (
	file_pkg_workload_proto_knative_integration_proto_rawDescOnce sync.Once
	file_pkg_workload_proto_knative_integration_proto_rawDescData []byte
)

func file_pkg_workload_proto_knative_integration_proto_rawDescGZIP() []byte {
	file_pkg_workload_proto_knative_integration_proto_rawDescOnce.Do(func() {
		file_pkg_workload_proto_knative_integration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_workload_proto_knative_integration_proto_rawDesc), len(file_pkg_workload_proto_knative_integration_proto_rawDesc)))
	})
	return file_pkg_workload_proto_knative_integration_proto_rawDescData
}

var file_pkg_workload_proto_knative_integration_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_workload_proto_knative_integration_proto_goTypes = []any{
	(*AddVMRequest)(nil),           // 0: proto.AddVMRequest
	(*AddVMResponse)(nil),          // 1: proto.AddVMResponse
	(*RemoveVMRequest)(nil),        // 2: proto.RemoveVMRequest
	(*RemoveVMResponse)(nil),       // 3: proto.RemoveVMResponse
	(*DestroyAllRequest)(nil),      // 4: proto.DestroyAllRequest
	(*DestroyAllResponse)(nil),     // 5: proto.DestroyAllResponse
	(*CreateSnapshotRequest)(nil),  // 6: proto.CreateSnapshotRequest
	(*CreateSnapshotResponse)(nil), // 7: proto.CreateSnapshotResponse
}
var file_pkg_workload_proto_knative_integration_proto_depIdxs = []int32{
	0, // 0: proto.KhalaKnativeIntegration.AddVM:input_type -> proto.AddVMRequest
	2, // 1: proto.KhalaKnativeIntegration.RemoveVM:input_type -> proto.RemoveVMRequest
	4, // 2: proto.KhalaKnativeIntegration.DestroyAll:input_type -> proto.DestroyAllRequest
	6, // 3: proto.KhalaKnativeIntegration.CreateSnapshot:input_type -> proto.CreateSnapshotRequest
	1, // 4: proto.KhalaKnativeIntegration.AddVM:output_type -> proto.AddVMResponse
	3, // 5: proto.KhalaKnativeIntegration.RemoveVM:output_type -> proto.RemoveVMResponse
	5, // 6: proto.KhalaKnativeIntegration.DestroyAll:output_type -> proto.DestroyAllResponse
	7, // 7: proto.KhalaKnativeIntegration.CreateSnapshot:output_type -> proto.CreateSnapshotResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_workload_proto_knative_integration_proto_init() }
func file_pkg_workload_proto_knative_integration_proto_init() {
	if File_pkg_workload_proto_knative_integration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_workload_proto_knative_integration_proto_rawDesc), len(file_pkg_workload_proto_knative_integration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_workload_proto_knative_integration_proto_goTypes,
		DependencyIndexes: file_pkg_workload_proto_knative_integration_proto_depIdxs,
		MessageInfos:      file_pkg_workload_proto_knative_integration_proto_msgTypes,
	}.Build()
	File_pkg_workload_proto_knative_integration_proto = out.File
	file_pkg_workload_proto_knative_integration_proto_goTypes = nil
	file_pkg_workload_proto_knative_integration_proto_depIdxs = nil
}
