// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: nexus_rpc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NexusRPCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NexusRPCRequest) Reset() {
	*x = NexusRPCRequest{}
	mi := &file_nexus_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NexusRPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NexusRPCRequest) ProtoMessage() {}

func (x *NexusRPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NexusRPCRequest.ProtoReflect.Descriptor instead.
func (*NexusRPCRequest) Descriptor() ([]byte, []int) {
	return file_nexus_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *NexusRPCRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *NexusRPCRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type NexusRPCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NexusRPCResponse) Reset() {
	*x = NexusRPCResponse{}
	mi := &file_nexus_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NexusRPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NexusRPCResponse) ProtoMessage() {}

func (x *NexusRPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NexusRPCResponse.ProtoReflect.Descriptor instead.
func (*NexusRPCResponse) Descriptor() ([]byte, []int) {
	return file_nexus_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *NexusRPCResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *NexusRPCResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_nexus_rpc_proto protoreflect.FileDescriptor

const file_nexus_rpc_proto_rawDesc = "" +
	"\n" +
	"\x0fnexus_rpc.proto\x12\x05proto\"=\n" +
	"\x0fNexusRPCRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\">\n" +
	"\x10NexusRPCResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload2O\n" +
	"\x0eNexusRPCServer\x12=\n" +
	"\bNexusRPC\x12\x16.proto.NexusRPCRequest\x1a\x17.proto.NexusRPCResponse\"\x00B+Z)github.com/JooyoungPark73/khala/pkg/protob\x06proto3"

var (
	file_nexus_rpc_proto_rawDescOnce sync.Once
	file_nexus_rpc_proto_rawDescData []byte
)

func file_nexus_rpc_proto_rawDescGZIP() []byte {
	file_nexus_rpc_proto_rawDescOnce.Do(func() {
		file_nexus_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nexus_rpc_proto_rawDesc), len(file_nexus_rpc_proto_rawDesc)))
	})
	return file_nexus_rpc_proto_rawDescData
}

var file_nexus_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nexus_rpc_proto_goTypes = []any{
	(*NexusRPCRequest)(nil),  // 0: proto.NexusRPCRequest
	(*NexusRPCResponse)(nil), // 1: proto.NexusRPCResponse
}
var file_nexus_rpc_proto_depIdxs = []int32{
	0, // 0: proto.NexusRPCServer.NexusRPC:input_type -> proto.NexusRPCRequest
	1, // 1: proto.NexusRPCServer.NexusRPC:output_type -> proto.NexusRPCResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nexus_rpc_proto_init() }
func file_nexus_rpc_proto_init() {
	if File_nexus_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexus_rpc_proto_rawDesc), len(file_nexus_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nexus_rpc_proto_goTypes,
		DependencyIndexes: file_nexus_rpc_proto_depIdxs,
		MessageInfos:      file_nexus_rpc_proto_msgTypes,
	}.Build()
	File_nexus_rpc_proto = out.File
	file_nexus_rpc_proto_goTypes = nil
	file_nexus_rpc_proto_depIdxs = nil
}
