// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: pkg/workload/proto/nexus_rpc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NexusRPCServer_NexusRPC_FullMethodName = "/proto.NexusRPCServer/NexusRPC"
)

// NexusRPCServerClient is the client API for NexusRPCServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NexusRPCServerClient interface {
	NexusRPC(ctx context.Context, in *NexusRPCRequest, opts ...grpc.CallOption) (*NexusRPCResponse, error)
}

type nexusRPCServerClient struct {
	cc grpc.ClientConnInterface
}

func NewNexusRPCServerClient(cc grpc.ClientConnInterface) NexusRPCServerClient {
	return &nexusRPCServerClient{cc}
}

func (c *nexusRPCServerClient) NexusRPC(ctx context.Context, in *NexusRPCRequest, opts ...grpc.CallOption) (*NexusRPCResponse, error) {
	out := new(NexusRPCResponse)
	err := c.cc.Invoke(ctx, NexusRPCServer_NexusRPC_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NexusRPCServerServer is the server API for NexusRPCServer service.
// All implementations must embed UnimplementedNexusRPCServerServer
// for forward compatibility
type NexusRPCServerServer interface {
	NexusRPC(context.Context, *NexusRPCRequest) (*NexusRPCResponse, error)
	mustEmbedUnimplementedNexusRPCServerServer()
}

// UnimplementedNexusRPCServerServer must be embedded to have forward compatible implementations.
type UnimplementedNexusRPCServerServer struct {
}

func (UnimplementedNexusRPCServerServer) NexusRPC(context.Context, *NexusRPCRequest) (*NexusRPCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NexusRPC not implemented")
}
func (UnimplementedNexusRPCServerServer) mustEmbedUnimplementedNexusRPCServerServer() {}

// UnsafeNexusRPCServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NexusRPCServerServer will
// result in compilation errors.
type UnsafeNexusRPCServerServer interface {
	mustEmbedUnimplementedNexusRPCServerServer()
}

func RegisterNexusRPCServerServer(s grpc.ServiceRegistrar, srv NexusRPCServerServer) {
	s.RegisterService(&NexusRPCServer_ServiceDesc, srv)
}

func _NexusRPCServer_NexusRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NexusRPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusRPCServerServer).NexusRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusRPCServer_NexusRPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusRPCServerServer).NexusRPC(ctx, req.(*NexusRPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NexusRPCServer_ServiceDesc is the grpc.ServiceDesc for NexusRPCServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NexusRPCServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NexusRPCServer",
	HandlerType: (*NexusRPCServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NexusRPC",
			Handler:    _NexusRPCServer_NexusRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/workload/proto/nexus_rpc.proto",
}
