apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/hyhe/trace-func-py:latest
          ports:
            - name: h2c # For gRPC support
              containerPort: 80