# Tenant custom configs
tenant:
  name: myminio
  configuration:
    configSecret:
      name: myminio-env-configuration
      accessKey: minio
      secretKey: minio123
  pools:
    - servers: 1 # Must be either 1 or >= 4
      name: pool-0
      volumesPerServer: 1
      size: 700Gi
      nodeSelector:
        minio-type: tenant
      storageClassName: local-storage
  metrics:
    enabled: true
  certificate:
    requestAutoCert: false
  prometheusOperator: true
  env:
  - name: MINIO_PROMETHEUS_URL
    value: "http://prometheus-kube-prometheus-prometheus.monitoring:9090"
  - name: PROMETHEUS_NAMESPACE
    value: "monitoring"
  - name: MINIO_PROMETHEUS_AUTH_TYPE
    value: "public"
  - name: MINIO_STORAGE_CLASS_STANDARD
    value: "EC:0"
  - name: MINIO_STORAGE_CLASS_RRS
    value: "EC:0"
  - name: MINIO_SCANNER_SPEED
    value: "default"

ingress:
  api:
    enabled: true
    ingressClassName: ""
    annotations:
      kubernetes.io/ingress.class: "istio"
    host: myminio-api.minio.10.200.3.4.sslip.io
    path: /
    pathType: Prefix
  console:
    enabled: false