# MIT License

# Copyright (c) 2024 EASE lab

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


## Database ----------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processing-database
  namespace: default
spec:
  selector:
    matchLabels:
      app: video-processing-database
  template:
    metadata:
      labels:
        app: video-processing-database
    spec:
      containers:
      - name: database
        image: docker.io/vhiveease/mongodb
        ports:
        - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: video-processing-database
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: video-processing-database
  ports:
  - name: database
    port: 27017
    targetPort: 27017

---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-video-processing-database
spec:
  template:
    spec:
      containers:
      - name: init-video-processing-database
        image: docker.io/vhiveease/video-processing-init-database:latest
        args:
          - --db_addr=mongodb://video-processing-database:27017
      restartPolicy: Never