// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/faas/faas.proto

package faas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request message containing the function input (string).
type FaasRequest struct {
	Input                string   `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Runtime              uint32   `protobuf:"varint,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Memory               uint32   `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FaasRequest) Reset()         { *m = FaasRequest{} }
func (m *FaasRequest) String() string { return proto.CompactTextString(m) }
func (*FaasRequest) ProtoMessage()    {}
func (*FaasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d268738091211865, []int{0}
}

func (m *FaasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaasRequest.Unmarshal(m, b)
}
func (m *FaasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaasRequest.Marshal(b, m, deterministic)
}
func (m *FaasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaasRequest.Merge(m, src)
}
func (m *FaasRequest) XXX_Size() int {
	return xxx_messageInfo_FaasRequest.Size(m)
}
func (m *FaasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FaasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FaasRequest proto.InternalMessageInfo

func (m *FaasRequest) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *FaasRequest) GetRuntime() uint32 {
	if m != nil {
		return m.Runtime
	}
	return 0
}

func (m *FaasRequest) GetMemory() uint32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

// Response message containing the execution latency (microseconds).
type FaasReply struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Latency              int64    `protobuf:"varint,2,opt,name=latency,proto3" json:"latency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FaasReply) Reset()         { *m = FaasReply{} }
func (m *FaasReply) String() string { return proto.CompactTextString(m) }
func (*FaasReply) ProtoMessage()    {}
func (*FaasReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d268738091211865, []int{1}
}

func (m *FaasReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaasReply.Unmarshal(m, b)
}
func (m *FaasReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaasReply.Marshal(b, m, deterministic)
}
func (m *FaasReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaasReply.Merge(m, src)
}
func (m *FaasReply) XXX_Size() int {
	return xxx_messageInfo_FaasReply.Size(m)
}
func (m *FaasReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FaasReply.DiscardUnknown(m)
}

var xxx_messageInfo_FaasReply proto.InternalMessageInfo

func (m *FaasReply) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func (m *FaasReply) GetLatency() int64 {
	if m != nil {
		return m.Latency
	}
	return 0
}

func init() {
	proto.RegisterType((*FaasRequest)(nil), "faasfunction.FaasRequest")
	proto.RegisterType((*FaasReply)(nil), "faasfunction.FaasReply")
}

func init() { proto.RegisterFile("pkg/faas/faas.proto", fileDescriptor_d268738091211865) }

var fileDescriptor_d268738091211865 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x8d, 0xc5, 0xfe, 0x19, 0xf5, 0xb2, 0x8a, 0xc6, 0x9e, 0x4a, 0x2e, 0xd6, 0x83, 0x09,
	0xe8, 0x07, 0x10, 0x05, 0xbd, 0x78, 0x0b, 0x78, 0xf1, 0x36, 0x8d, 0xd3, 0x36, 0xb8, 0xd9, 0x59,
	0x77, 0x67, 0xc1, 0xfd, 0xf6, 0xd2, 0xa4, 0x91, 0x1c, 0x7a, 0x19, 0xe6, 0xc7, 0x83, 0x1f, 0x8f,
	0x07, 0x17, 0xf6, 0x7b, 0x53, 0xac, 0x11, 0x7d, 0x7b, 0x72, 0xeb, 0x58, 0x58, 0x9d, 0xed, 0xfe,
	0x75, 0x30, 0x95, 0xd4, 0x6c, 0xb2, 0x0f, 0x38, 0x7d, 0x43, 0xf4, 0x25, 0xfd, 0x04, 0xf2, 0xa2,
	0x2e, 0xe1, 0xa4, 0x36, 0x36, 0x48, 0x9a, 0x2c, 0x92, 0xe5, 0xac, 0xec, 0x40, 0xa5, 0x30, 0x71,
	0xc1, 0x48, 0xdd, 0x50, 0x7a, 0xbc, 0x48, 0x96, 0xe7, 0x65, 0x8f, 0xea, 0x0a, 0xc6, 0x0d, 0x35,
	0xec, 0x62, 0x3a, 0x6a, 0x83, 0x3d, 0x65, 0xcf, 0x30, 0xeb, 0xb4, 0x56, 0x47, 0x35, 0x87, 0xa9,
	0x23, 0x6f, 0xd9, 0x78, 0xda, 0x7b, 0xff, 0x79, 0xa7, 0xd6, 0x28, 0x64, 0xaa, 0xd8, 0xaa, 0x47,
	0x65, 0x8f, 0x0f, 0xef, 0x30, 0x7d, 0xfd, 0xa5, 0x2a, 0x08, 0x3b, 0xf5, 0x04, 0x93, 0xee, 0x27,
	0x75, 0x93, 0x0f, 0xfb, 0xe7, 0x83, 0xf2, 0xf3, 0xeb, 0x43, 0x91, 0xd5, 0x31, 0x3b, 0x7a, 0xb9,
	0xfb, 0xbc, 0xdd, 0xd4, 0xb2, 0x0d, 0xab, 0xbc, 0xe2, 0xa6, 0x20, 0xd9, 0xde, 0x13, 0x7a, 0x5d,
	0x10, 0xfa, 0xa8, 0x19, 0xbf, 0xc8, 0x15, 0xfd, 0x54, 0xab, 0x71, 0x3b, 0xd3, 0xe3, 0x5f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xc8, 0xda, 0x9e, 0x1a, 0x3d, 0x01, 0x00, 0x00,
}
