// Python Compile: python3 -m grpc_tools.protoc faasfunction.proto -I=. --python_out=. --grpc_python_out=.
// Alternative Python Compile: protoc
// GO Compile:

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: faasfunction.proto

package faas

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message containing the function input (string)
type FaasRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input   string `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Runtime uint32 `protobuf:"varint,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Memory  uint32 `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"`
}

func (x *FaasRequest) Reset() {
	*x = FaasRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_faasfunction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FaasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaasRequest) ProtoMessage() {}

func (x *FaasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faasfunction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaasRequest.ProtoReflect.Descriptor instead.
func (*FaasRequest) Descriptor() ([]byte, []int) {
	return file_faasfunction_proto_rawDescGZIP(), []int{0}
}

func (x *FaasRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *FaasRequest) GetRuntime() uint32 {
	if x != nil {
		return x.Runtime
	}
	return 0
}

func (x *FaasRequest) GetMemory() uint32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

// Response message containing the execution latency (microseconds)
type FaasReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Latency  int64  `protobuf:"varint,2,opt,name=latency,proto3" json:"latency,omitempty"`
}

func (x *FaasReply) Reset() {
	*x = FaasReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_faasfunction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FaasReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaasReply) ProtoMessage() {}

func (x *FaasReply) ProtoReflect() protoreflect.Message {
	mi := &file_faasfunction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaasReply.ProtoReflect.Descriptor instead.
func (*FaasReply) Descriptor() ([]byte, []int) {
	return file_faasfunction_proto_rawDescGZIP(), []int{1}
}

func (x *FaasReply) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *FaasReply) GetLatency() int64 {
	if x != nil {
		return x.Latency
	}
	return 0
}

var File_faasfunction_proto protoreflect.FileDescriptor

var file_faasfunction_proto_rawDesc = []byte{
	0x0a, 0x12, 0x66, 0x61, 0x61, 0x73, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x66, 0x61, 0x61, 0x73, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x55, 0x0a, 0x0b, 0x46, 0x61, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x22, 0x41, 0x0a, 0x09, 0x46, 0x61, 0x61,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x32, 0x4b, 0x0a, 0x08,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x12, 0x3f, 0x0a, 0x07, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x66, 0x61, 0x61, 0x73, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x46, 0x61, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x66, 0x61, 0x61, 0x73, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x61,
	0x61, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x1a, 0x5a, 0x18, 0x62, 0x65, 0x6e,
	0x63, 0x68, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x2f, 0x66, 0x61, 0x61, 0x73, 0x66, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_faasfunction_proto_rawDescOnce sync.Once
	file_faasfunction_proto_rawDescData = file_faasfunction_proto_rawDesc
)

func file_faasfunction_proto_rawDescGZIP() []byte {
	file_faasfunction_proto_rawDescOnce.Do(func() {
		file_faasfunction_proto_rawDescData = protoimpl.X.CompressGZIP(file_faasfunction_proto_rawDescData)
	})
	return file_faasfunction_proto_rawDescData
}

var file_faasfunction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_faasfunction_proto_goTypes = []interface{}{
	(*FaasRequest)(nil), // 0: faasfunction.FaasRequest
	(*FaasReply)(nil),   // 1: faasfunction.FaasReply
}
var file_faasfunction_proto_depIdxs = []int32{
	0, // 0: faasfunction.Executor.Execute:input_type -> faasfunction.FaasRequest
	1, // 1: faasfunction.Executor.Execute:output_type -> faasfunction.FaasReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_faasfunction_proto_init() }
func file_faasfunction_proto_init() {
	if File_faasfunction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_faasfunction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FaasRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_faasfunction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FaasReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_faasfunction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_faasfunction_proto_goTypes,
		DependencyIndexes: file_faasfunction_proto_depIdxs,
		MessageInfos:      file_faasfunction_proto_msgTypes,
	}.Build()
	File_faasfunction_proto = out.File
	file_faasfunction_proto_rawDesc = nil
	file_faasfunction_proto_goTypes = nil
	file_faasfunction_proto_depIdxs = nil
}
