name: Code quality checks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


env:
  GOOS: linux
  GO111MODULE: on

jobs:
  golangci:
    name: GolangCI Lint
    runs-on: ubuntu-24.04
    strategy:
      matrix: { dir: ['cmd', 'pkg', 'tools/plotter'] }
      fail-fast: false
    steps:
      - name: Checkout code into go module directory
        uses: actions/checkout@v6
    
      - name: Set up Go version in go.mod file
        uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod
          cache-dependency-path: |
            ./go.mod
            ./go.sum

      - name: Install dependencies for cgo
        run: sudo apt update && sudo apt install libsnmp-dev

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v9.3.0
        with:
          working-directory: ${{ matrix.dir }}
          args: --timeout 5m
