name: Unit tests

on:
 push:
   branches: [ main ]
   paths-ignore:
     - 'docs/**'
     - '**.md'
 pull_request:
   branches: [ main ]
   paths-ignore:
     - 'docs/**'
     - '**.md'
 workflow_dispatch:

env:
  GOOS: linux
  GO111MODULE: on

jobs:
  unit_tests:
    name: Build and test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        module:
          [
              config,
              driver,
              generator,
              trace,
          ]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'

      - uses: actions/setup-go@v5
        with:
          go-version: 1.19

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('tools/trace_synthesizer/requirements.txt') }}

      - name: Install requirements
        run: pip install -r ./tools/trace_synthesizer/requirements.txt

      - name: Build loader
        run: go build cmd/loader.go

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

      - name: Install requirements
        run: pip install -r ./requirements.txt

      - name: Run loader tests
        run: go test -v -cover -race ./pkg/${{ matrix.module }}
